# Generated by Django 5.1.1 on 2025-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicationApartmentMediation", "0002_remove_user_status_user_status1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="images",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
