# Generated by Django 5.1.1 on 2025-01-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicationApartmentMediation",
            "0003_rename_images_image_image_alter_address_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="status1",
            new_name="status",
        ),
    ]
