# Generated by Django 5.1.1 on 2025-01-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applicationApartmentMediation", "0005_request"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Request",
        ),
    ]
